apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-building-apps-svc"
  labels:
    app: kubeacademy
spec:
  selector:
    app: kubeacademy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000