apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: mmertdogann/building-apps
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
